### ISSUE TITLE
Error when disable network.

### ISSUE THREAD

**Issue by frankenten13** [mnayef95/UReflection#1]
Good library, but i see this bug. When i disable network, run error when call  UReflection.bind(this);
Can you fix it? Thanks
`FATAL EXCEPTION: main
                                                                      Process: com.mnayef.utilsexam, PID: 29478
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mnayef.utilsexam/com.mnayef.utilsexam.MainActivity}: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                       Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                          at com.mnayef.utils.reflection.UReflection.bindField(UReflection.java:56)
                                                                          at com.mnayef.utils.reflection.UReflection.bind(UReflection.java:40)
                                                                          at com.mnayef.utilsexam.MainActivity.onCreate(MainActivity.java:118)
                                                                          at android.app.Activity.performCreate(Activity.java:6942)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                          at com.mnayef.utils.reflection.UReflection.bindField(UReflection.java:51)
                                                                          at com.mnayef.utils.reflection.UReflection.bind(UReflection.java:40) 
                                                                          at com.mnayef.utilsexam.MainActivity.onCreate(MainActivity.java:118) 
                                                                          at android.app.Activity.performCreate(Activity.java:6942) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.NetworkInfo.getType()' on a null object reference
                                                                          at com.mnayef.utils.NetUtils.isWifi(NetUtils.java:82)
                                                                          at com.mnayef.utilsexam.MainActivityUtils.<init>(MainActivityUtils.java:67)
                                                                          at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                          at com.mnayef.utils.reflection.UReflection.bindField(UReflection.java:51) 
                                                                          at com.mnayef.utils.reflection.UReflection.bind(UReflection.java:40) 
                                                                          at com.mnayef.utilsexam.MainActivity.onCreate(MainActivity.java:118) 
                                                                          at android.app.Activity.performCreate(Activity.java:6942) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) `

**Comment by mnayef95** [comment]
what is android sdk version?

**Comment by frankenten13** [comment]
i use Galaxy Note5( SM-N920C) run Android SDK 24

**Comment by mnayef95** [comment]
Fixed in v1.2.1
